/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libsjf_AlgoritmoJNI */

#ifndef _Included_libsjf_AlgoritmoJNI
#define _Included_libsjf_AlgoritmoJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libsjf_AlgoritmoJNI
 * Method:    scheduleSJF
 * Signature: ([I[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_libsjf_AlgoritmoJNI_scheduleSJF
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
